[MM-30033] Add additional developer setup instructions
mattermost/mattermost-app-zendesk pull request #64
Opened 2021-07-09 16:45 UTC by jfrerich

#### Summary
update README with instructions for connecting MM server to zendesk cloud

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36879

2021-07-09 17:02 UTC, mickmister requested changes

2021-07-09 17:02 UTC, mickmister commented on README.md
> +To allow the Mattermost server to communicate with a Zendesk cloud instance, you must expose your local mattermost instance via a tool such as ngrok.io. Set the `MM_SERVICESETTINGS_SITEURL` environme
```suggestion
To allow the Mattermost server to communicate with a Zendesk cloud instance, your Mattermost instance needs to be exposed to the internet via a tool such as [ngrok.io](https://ngrok.io). The Mattermost server then needs to be configured to use the exposed address. You can set it in the system console at `System Console` > `ENVIRONMENT` > `Web Server` > `Site URL`, or set the `MM_SERVICESETTINGS_SITEURL` environment variable. You'll need to restart your Mattermost server after you change the Site URL. You can ensure the URL is correct by clicking "Test Live URL" in the system console page mentioned above.
```

2021-07-12 14:17 UTC, jfrerich commented on README.md
> +To allow the Mattermost server to communicate with a Zendesk cloud instance, you must expose your local mattermost instance via a tool such as ngrok.io. Set the `MM_SERVICESETTINGS_SITEURL` environme
Much better.  Thank you sir :)

2021-07-12 14:28 UTC, jfrerich commented on README.md
> +`/apps install http com.mattermost.zendesk`
You are correct.  An `http` install uses the URL and an `aws` install uses the pluginID.  For the install instructions, I should probably use the AWS instructions, correct?

2021-07-12 15:39 UTC, mickmister commented on README.md
> +`/apps install http com.mattermost.zendesk`
For installing in a development environment (what this section describes), I suggest using the http install version. If I were to add any features to this project, I would want to use the http mode so I can be up and running quick. What value does the aws deployment give the developer that is working on the App?

2021-07-15 14:22 UTC, jfrerich commented on README.md
> +`/apps install http com.mattermost.zendesk`
👍 you're correct.  This is for development and should use `http` not `aws`.

2021-07-22 03:38 UTC, mickmister approved these changes

2021-08-30 19:07 UTC, justinegeffen commented on README.md
> +To allow the Mattermost server to communicate with a Zendesk cloud instance, your Mattermost instance needs to be exposed to the internet via a tool such as [ngrok.io](https://ngrok.io). The Mattermo
```suggestion
To allow the Mattermost server to communicate with a Zendesk cloud instance, your Mattermost instance needs to be exposed to the internet via a tool such as [ngrok.io](https://ngrok.io). The Mattermost server then needs to be configured to use the exposed address. You can set it via **System Console > ENVIRONMENT > Web Server > Site URL**. Then select **Test Live URL** to confirm that the URL is correct. You can also set the `MM_SERVICESETTINGS_SITEURL` environment variable. 

You'll need to restart your Mattermost server after you change the Site URL. 
```

2021-08-30 19:07 UTC, justinegeffen approved these changes

2021-10-12 12:24 UTC, cpanato commented
/check-cla

2021-11-23 16:22 UTC, merged