[MM-40467] Fix panic if oauth2user is empty
mattermost/mattermost-app-zendesk pull request #91
Opened 2021-12-03 10:45 UTC by hanzei

#### Summary
If the oauth2 user is not set, the app should not try to access the data. I'm proposing a defensive approach here, which every time checks if the data is there.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40467

2021-12-03 15:41 UTC, jfrerich approved these changes

2021-12-03 16:46 UTC, mickmister requested changes
Just one request to do a `falsy` comparison rather than an explicit empty string comparison on one of the checks.

Also, should the code following the spots modified in this PR be changed to react to the fact that the value may be undefined?

2021-12-03 16:46 UTC, mickmister commented on src/utils/utils.ts
> +    if (oauth2user?.token?.access_token !== '') {
In this case `access_token` will be `undefined`, and we will incorrectly assumed it's defined when we assert that it's not the empty string. An empty string is [treated as falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) so the check below will work:

```suggestion
    if (oauth2user?.token?.access_token) {
```

@jfrerich Any reason for the explicit empty string comparison in the existing code?

2021-12-06 14:43 UTC, mickmister commented
Currently blocking on my comment:

> Also, should the code following the spots modified in this PR be changed to react to the fact that the value may be undefined?

The current change in the PR may result in panics further down in the functions that were edited, or functions that receive these objects containing the edited values. @jfrerich Can you please take a look at the code paths here?

2021-12-09 11:17 UTC, hanzei commented
> The current change in the PR may result in panics further down in the functions that were edited, or functions that receive these objects containing the edited values. @jfrerich Can you please take a look at the code paths here?

@mickmister I don' think there is an issue here. The access token is only being used in `newZDClient`, which checks if it's set: https://github.com/mattermost/mattermost-app-zendesk/blob/042d0e50d0f60949e28eda0e9030ca4632676f65/src/clients/zendesk.ts#L67-L69

Calls to `newZDClient` are mostly guarded with a `catch`. The only one missing a catch is `fCreateTarget`. Should we add that?

2021-12-09 15:30 UTC, mickmister commented
@hanzei Thanks for going through the code more thoroughly to check for other issues :+1:

> The only one missing a catch is `fCreateTarget`. Should we add that?

If the improvement is easy to add, sure why not add it here. The original problem here is only with the OAuth complete call (I think) so it's not necessary to introduce the error catch in this PR, but it doesn't hurt to add more defensive code when we see the opportunity.

2021-12-10 08:31 UTC, hanzei commented
@mickmister Added a catch around it. Maybe it's worth opening a (HW?) ticket to add a `catch` for all `CallResponseHandler`'s?

2022-02-25 12:49 UTC, hanzei commented
@mickmister Gentle reminder to review this PR

2022-02-25 17:00 UTC, mickmister approved these changes

2022-02-28 10:00 UTC, hanzei commented
@DHaussermann Heads up that I'm going to merge this PR as it is as it's it only adds more defensive code and error checks and blocks the review on https://github.com/mattermost/mattermost-app-zendesk/pull/90.

2022-02-28 10:00 UTC, merged